Using options "-Lkv" with curl when running the configuration checks
NASA-AMMOS/common-workflow-service pull request #42
Opened 2021-05-05 18:10 UTC by LucaCinquini

Hi, I noticed that the configuration process fails when using your own Elasticsearch with a non-standard certificate, such as the ones issued by JPL. This PR should make the configuration process complete correctly.

2021-10-06 20:13 UTC, ztaylor54 requested changes
Thanks for this PR, @LucaCinquini! Should be an easy merge with a few slight changes I've noted in my review.

2021-10-06 20:13 UTC, ztaylor54 commented on cws-installer/src/main/java/jpl/cws/task/CwsInstaller.java
> +				cmdArray = new String[] {"curl", "-Lkv", "--fail", "-u", elasticsearch_username + ":" + elasticsearch_password, "https://" + elasticsearch_host + ":" + elasticsearch_port + "/_cluster/health"};
@LucaCinquini Is `-k` the only necessary option to add here? I'm not sure it's necessary to follow redirects & add verbosity to the response. 

The [docs for -k](https://curl.se/docs/manpage.html#-k) would suggest that it's the only necessary option to ignore invalid / unrecognized certs.

2021-10-06 20:13 UTC, ztaylor54 commented on cws-installer/src/main/java/jpl/cws/task/CwsInstaller.java
> +			print(String.join(" ", cmdArray));
Please remove these debug print statements, as they conflict with [later output formatting](https://github.com/NASA-AMMOS/common-workflow-service/blob/5a55b3de64fd17ce9edc6f6e6fbc3b706e8e9c8d/cws-installer/src/main/java/jpl/cws/task/CwsInstaller.java#L1830).

2022-01-10 15:03 UTC, LucaCinquini commented
Sorry for the very late action on this. I removed the print statements and only kept the "-k" option.
Please go ahead and merge this PR if possible. Thanks.

2022-01-10 22:11 UTC, Gillingham commented
Wouldnt adding the custom CA to your systems trust store which curl uses be a better path than having curl ignore cert errors/trust issues?

2022-01-10 22:23 UTC, LucaCinquini commented
This is actually the JPL CA, which is not part of the standard package. Yes adding the CA to each truststore is possible, but it's quite a bit of work for the user, and you need to do it in every environment you deploy CWS, and every time you upgrade the system... Quite painful.

2022-01-10 22:27 UTC, Gillingham commented
If you don't add the CA to your system trusted CA list you need to do this sort of workaround with every piece of software on each host too. Putting the CA in a directory and running the update CA command isn't a lot of work compared with that. 

Say CWS runs python workers, or another application, you now have to figure out the correct way to add a custom CA trust to each script or language interpreter etc, or disable TLS verification like this, both those options should not be encouraged.

2022-01-10 22:37 UTC, LucaCinquini commented
Yes you are right. Adding "-k" to the installation script is a simple change to allow the installation to proceed without too much work, when you deploy for testing. In a production environment you would definitely want to trust your CA.

2022-04-18 19:55 UTC, voxparcxls commented
@Gillingham 
Would adding a development/testing prompt during installation be a good way to make the "-k" curl option distinct from production? How could we make this more simple?

2023-03-16 04:37 UTC, jamesfwood commented
We have decided not to merge this PR and close it because it could compromise security in a production system.  If we want to explore this more, we should think of another way to make this work only for development environments.  Thanks!

2023-03-16 04:37 UTC, closed without merging