fix: Console Worker ID
NASA-AMMOS/common-workflow-service pull request #76
Opened 2021-12-08 23:23 UTC by voxparcxls

2021-12-14 20:51 UTC, voxparcxls commented on cws-engine-service/src/main/java/jpl/cws/engine/EngineDbService.java
> +	public boolean workerConsoleOnlyTypeExists() {
* Check method added to search for existing `console_only` row

2021-12-14 20:51 UTC, voxparcxls commented on cws-engine-service/src/main/java/jpl/cws/engine/EngineDbService.java
> +		return jdbcTemplate.queryForObject("SELECT count(*) FROM cws_worker WHERE cws_install_type=?", new Object[]{cwsInstallType}, Integer.class) > 0;
* Check method added to search for existing `console_only` row

2021-12-14 22:28 UTC, ztaylor54 requested changes

2021-12-14 22:28 UTC, ztaylor54 commented on cws-engine-service/src/main/java/jpl/cws/engine/EngineDbService.java
> +				log.info("Worker Row with cws_install_type: " + cwsInstallType + ", already exists. ");
Should this be an error?

2021-12-14 22:28 UTC, ztaylor54 commented on cws-engine-service/src/main/java/jpl/cws/engine/EngineDbService.java
> +						workerName = "worker-" + "0000";
As per #54, this should be 

```suggestion
						workerName = "worker0000";
```

2021-12-14 22:39 UTC, ztaylor54 commented on cws-engine-service/src/main/java/jpl/cws/engine/EngineDbService.java
> +				log.info("Worker Row with cws_install_type: " + cwsInstallType + ", already exists. ");
Let's actually make this a warning
```suggestion
				log.warn("Worker Row with cws_install_type: " + cwsInstallType + ", already exists. ");
```

2021-12-14 23:03 UTC, voxparcxls commented on cws-engine-service/src/main/java/jpl/cws/engine/EngineDbService.java
> +				log.info("Worker Row with cws_install_type: " + cwsInstallType + ", already exists. ");
@ztaylor54  
Yes, changed that. Thanks

2021-12-14 23:06 UTC, voxparcxls commented
@galenatjpl  , This fix is ready for merge. Thanks!

2021-12-14 23:58 UTC, galenatjpl commented on cws-engine-service/src/main/java/jpl/cws/engine/EngineDbService.java
> +				log.info("Worker Row with cws_install_type: " + cwsInstallType + ", already exists. ");
or an "error"

2021-12-22 23:18 UTC, ztaylor54 approved these changes
LGTM!

2021-12-22 23:18 UTC, merged